### Create User
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password123456",
  "profileRole": "CUSTOMER"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "R1>otB=q/rX]8pwQ"
}