### Create User
POST http://localhost:8080/api/auth/user
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "password123456",
  "profileRole": "CUSTOMER"
}

### Login
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email": "email2@email.com",
  "password": "password123456"
}

### Update
PUT http://localhost:8080/api/auth/user/8
Content-Type: application/json

{
  "email": "email2@email.com",
  "password": "password123456",
  "userId": 8
}